# frozen_string_literal: true

source "https://rubygems.org"

ruby RUBY_VERSION

DECIDIM_VERSION = "~> 0.27.0"

gem "decidim", DECIDIM_VERSION
gem "decidim-admin", DECIDIM_VERSION
gem "decidim-core", DECIDIM_VERSION
gem "decidim-slider", path: ".."

gem "bootsnap", "~> 1.7"
gem "faker", "~> 2.14"
gem "rspec", "~> 3.0"

group :development, :test do
  gem "byebug", "~> 11.0", platform: :mri

  gem "decidim-dev", DECIDIM_VERSION
end

group :development do
  gem "letter_opener_web", "~> 1.3"
  gem "listen", "~> 3.1"
  gem "rubocop-faker", "~> 1.1"
  gem "spring", "~> 2.0"
  gem "spring-watcher-listen", "~> 2.0"
  gem "web-console"
end

group :test do
  gem "codecov", require: false
end
